apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: ibis1
spec:  
  replicas: 1  
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 2  
      maxUnavailable: 0  
  template:  
    metadata:  
      labels:  
        app: ibis1
    spec:  
      containers:  
      - name: ibis1 
        image: xiechuan/centos721511jenkinsslave:1.0.0
        imagePullPolicy: IfNotPresent  
        env:
          - name: jenkinsParas
            value: "{'jenkinsUrl':'http://jenkins:8080','username':'admin','password':'admin','nodename':'ibis1'}"
        ports:  
        - containerPort: 8080  
          name: tomcat 
          protocol: TCP  
        - containerPort: 8082
          name: socket
          protocol: TCP


