kind: Service  
apiVersion: v1  
metadata:  
  labels:  
      app: ibis2 
  name: ibis2
spec:  
  ports:  
  - port: 8080  
    targetPort: 8080 
    nodePort: 40081
    name: tomcat  
  type: NodePort
  selector:  
    app: ibis2
