FROM xiechuan/ant1101:1.0.1
MAINTAINER xiechuan  <xiechuanj@gmail.com>


RUN yum install -y unzip && wget http://apache.osuosl.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
RUN unzip  apache-maven-3.3.9-bin.zip -d /opt/
